"""rename updated to updated_at

Revision ID: 1528387d633d
Revises: a8d25787e894
Create Date: 2026-08-17 19:45:31.562090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1528387d633d'
down_revision: Union[str, Sequence[str], None] = 'a8d25787e894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('projects', 'updated')
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('tasks', 'updated')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('updated', sa.DATETIME(), nullable=True))
    op.drop_column('tasks', 'updated_at')
    op.add_column('projects', sa.Column('updated', sa.DATETIME(), nullable=True))
    op.drop_column('projects', 'updated_at')
    # ### end Alembic commands ###
