"""Removed updated_at

Revision ID: 9a3574d85638
Revises: 1528387d633d
Create Date: 2026-08-19 12:08:59.104163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a3574d85638'
down_revision: Union[str, Sequence[str], None] = '1528387d633d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'updated_at')
    op.drop_column('tasks', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    op.add_column('projects', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
