"""add updated to tasks

Revision ID: de50fb82fcb1
Revises: dec3771714c8
Create Date: 2026-08-17 12:17:18.492371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de50fb82fcb1'
down_revision: Union[str, Sequence[str], None] = 'dec3771714c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('updated', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('tasks', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    op.drop_column('tasks', 'updated')
    # ### end Alembic commands ###
