"""add updated_at to tasks

Revision ID: dec3771714c8
Revises: 4277a6758429
Create Date: 2026-08-17 12:15:55.180420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dec3771714c8'
down_revision: Union[str, Sequence[str], None] = '4277a6758429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
